dataset_prefix: "acs_public_cov_medium"
batch_size:
  - 10
window_size:
  - 10
query_type: "mwem_pgm"
comparison_type: "all"
epsilon: 10.0
delta: 1e-09
num_runs: 3
org_seed: 1234
num_runs_for_plot: 1
batches_for_plot: 5
