dataset_prefix: "adult_small"
batch_size:
  - 10
window_size:
  - 10
time_int_type: "days"
time_int_quantity: 1
time_int_str: "1day"
data_encoding_type: "binarized"
query_type: "mwem_pgm"
comparison_type: "all"
epsilon: 10.0
delta: 1e-09
num_runs: 1
org_seed: 1234
start_from_batch_num: null
num_batches: 50
predicates_filename: "adult_predicates.json"
num_threads: 8
num_runs_for_plot: 1
batches_for_plot: 50