dataset_prefix: "acs_public_cov_medium"
batch_size:
  - 10
window_size:
  - 10
time_int_type: "days"
time_int_quantity: 1
time_int_str: "1day"
data_encoding_type: "ohe"
query_type: "mwem_pgm"
comparison_type: "all"
epsilon: 10.0
delta: 1e-09
num_runs: 10
org_seed: 1234
start_from_batch_num: null
num_batches: 25
predicates_filename: "acs_public_cov_predicates.json"
num_threads: 4
num_runs_for_plot: 1
batches_for_plot: 5