dataset_prefix: "adult_small"
batch_size:
  - 5
  - 10
window_size:
  - 1
  - 5
  - 10
time_int_type: "days"
time_int_quantity: 1
time_int_str: "1day"
data_encoding_type: "ohe"
query_type: "mwem_pgm"
comparison_type: "all"
epsilon: 10.0
delta: 1e-09
num_runs: 3
org_seed: 1234
start_from_batch_num: null
num_batches: 25
predicates_filename: "adult_predicates.json"
num_threads: 8
num_runs_for_plot: 3
batches_for_plot: 25