dataset_prefix: "ny_taxi_medium"
batch_size:
  - null
window_size:
  - null
time_int_type: "minutes"
time_int_quantity: 10
time_int_str: "10mins"
data_encoding_type: "binarized"
query_type: "mwem_pgm"
comparison_type: "all"
epsilon: 10.0
delta: 1e-09
num_runs: 3
org_seed: 1234
start_from_batch_num: null
num_batches: 50
predicates_filename: "ny_taxi_predicates.json"
num_threads: 4
num_runs_for_plot: 1
batches_for_plot: 5